import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { StoreProvider } from './StoreProvider'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
// import SaveInforUser from './auth/cookie/saveInforUser'
import RefreshToken from './auth/cookie/refresh-token'
import { ScrollArea } from '@/components/ui/scroll-area'
import Oauth from './auth/page'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <StoreProvider>
        <body className={inter.className}>
          <ToastContainer />
          {/* <Oauth /> */}
          <RefreshToken />
          {/* <ScrollArea className='h-full w-full rounded-md border'>{children}</ScrollArea> */}
          {children}
        </body>
      </StoreProvider>
    </html>
  )
}
